Support intelmpi + gfortran for ESMF
Without this fix, will get the error below even with intelmpi + ifort:

libmpifort.so.12: error adding symbols: DSO missing from command line
gmake[8]: *** [StandAlone_DynAdvCore.x] Error 1
ld: Code.GCHP/GCHP/Shared/Linux/lib/libfvdycore.a(fv_mp_mod.o): undefined reference to symbol 'mpi_comm_null_copy_fn_'

One possible explanation is that GCHP compiliation install invokes gcc even with CC=icc